name: irctc_railtel_sdk
description: IRCTCRailtel Aadhaar Verification SDK for Flutter
version: 1.0.0
homepage: https://irctcrailtel.in

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.0
  uuid: ^4.2.0
  android_intent_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
